### ISSUE TITLE
messy code

### ISSUE THREAD

**Issue by xuziheng1002** [Graylog2/apache-mod_log_gelf#10]
got the messages of apache accesslog ,but they are messy code...
how can i resolve it?

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
