### ISSUE TITLE
Unable to install the module on SUSE11 behind firewalls

### ISSUE THREAD

**Issue by PraveenAA1** [Graylog2/apache-mod_log_gelf#11]
installed json-c-0.11  but failing with the below error

error: Failed dependencies:
        json-c is needed by libapache2-mod-gelf-0.1.0-1.x86_64

**Comment by mariussturm** [comment]
That's right json-c is a dependency of the module. If your operating system is not offering a proper package please check 3rd party repos like OpenSuse: https://software.opensuse.org/search?utf8=%E2%9C%93&q=json-c&search_devel=false&search_unsupported=false&baseproject=openSUSE%3ALeap%3A42.2
