### ISSUE TITLE
X-forwarded-for and log_gelf

### ISSUE THREAD

**Issue by phcyso** [Graylog2/apache-mod_log_gelf#2]
Hi
Is there a way of capturing the x-forwarded-for header though this mod?

I have an elastic loadbalancer and then varnish in front of apache so the only remote ip's I see in graylog are the varnish servers.

In our apache conf we have 

```
SetEnvIf REMOTE_ADDR "(.+)" CLIENTIP=$1
  SetEnvIf X-Forwarded-For "^([0-9.]+)" CLIENTIP=$1
  LogFormat "%{CLIENTIP}e %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" trueip_combined
```

and the ip is being logged fine to file at the moment just not to graylog.

I tried using mod_remoteip to set the client value from the x-forwarded-for but no change on the graylog side.
Are there any plans to let headers be captured as well?

**Comment by mariussturm** [comment]
Currently there is no way og getting the header informations but this could be a nice addition. When I find some time I can take a look if it's possible.

**Comment by phcyso** [comment]
:+1:

**Comment by xavier84** [comment]
Effectivement 👍
