### ISSUE TITLE
request_duration_us must be type:long instead of string

### ISSUE THREAD

**Issue by colttt** [Graylog2/apache-mod_log_gelf#5]
Hello,

its fine you has remove the dot, but its still a string ;)
here a output from elasticsearch-mappings (look at type:long/string)

```
"request_duration_ms":{"type":"long"} <<-- i need
"request_duration_us":{"type":"string","index":"not_analyzed"} <<-- i get
```

best regards

**Comment by TinoWildenhain** [comment]
I have a patch which resolves this issue. 

Changed it into a pull request:

https://github.com/Graylog2/apache-mod_log_gelf/pull/9

How does this work? Do people vote for the patch?

**Comment by mariussturm** [comment]
This is fixed by https://github.com/Graylog2/apache-mod_log_gelf/pull/9
