### ISSUE TITLE
ap_log_perrror loading of module fails

### ISSUE THREAD

**Issue by raben2** [Graylog2/apache-mod_log_gelf#7]
When trying to load the mod_log_gelf.so on my dev box
Server version: Apache/2.2.15 (Unix)
Server built:   Oct 16 2014 14:48:21
CentOS release 6.6 (Final)

i get the error: 
`/etc/httpd/modules/mod_log_gelf.so: undefined symbol: ap_log_perror_`
when i try to startup the httpd 

I tried version 0.1.0 and 0.2.0

**Comment by mariussturm** [comment]
The libapr version on Centos6 is too old. Please update to Centos 7, I will put a note in the docs.

**Comment by pauldsmyth** [comment]
I have this issue, using Amazon linux so can't upgrade.

**Comment by joschi** [comment]
@pauldsmyth There are currently no plans to support old Linux distributions like that. PRs to make this project work with them are welcome, though.

**Comment by pauldsmyth** [comment]
Amazon Linux 2016.3 is not an old distribution. It's Amazon's own linux based on Centos 6. I don't have time to rewrite other people's code. I'll find another solution

**Comment by mariussturm** [comment]
@pauldsmyth there is always the possibility to sponsor a certain feature if you don't have the time yourself, just contact our sales: https://www.graylog.org/pages/contact_sales

**Comment by pauldsmyth** [comment]
That's worthy of serious consideration. Currently this isn't in production for us and once it is I'll be making a case for enterprise licencing so if I don't get this working using an alternative method I'll push for it.
